site_name: MIP Template Site
site_description: A template for Model Intercomparison Projects (MIPs) to stand up their own webpage
site_author: WCRP-CMIP
repo_url: https://github.com/WCRP-CMIP/MIP-template-theme
repo_name: WCRP-CMIP/MIP-template-theme

theme:
  name: shadcn
  palette:
    primary: blue
    accent: cyan

plugins:
  - search

nav:
  - Home: index.md
  - Developers:
    - Getting Started: developers/getting-started.md
    - Updating Content: developers/updating-content.md

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - toc:
      permalink: true

extra:
  version:
    provider: mike
